spring.application.name=fitness-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_tracker
spring.datasource.username=hristijanzaharchev
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=this-is-a-temporary-secret-key-change-it-later-1234567890

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2